//=============================================================================
// ds_defs.vh -- architectural constants for the DriveSentinel INT8 accelerator
//=============================================================================
// Hand-written. Everything here is a property of the ARCHITECTURE: widths, the
// memory map, the layer table. Everything that is a property of the EXPORTED
// MODEL -- the requantisation multipliers, the fractional width chosen by the
// sweep, the number of weights -- lives in ds_gen.vh, which is generated by
// scripts/rtl/gen_rtl_params.py from artifacts/int8_export/scales.json and must
// not be edited.
//
// The split matters: if the model is re-exported, ds_gen.vh changes and this file
// does not. tests/test_rtl_generated.py regenerates ds_gen.vh and fails if the
// committed copy differs, so a stale header cannot survive a re-export.
//=============================================================================

`ifndef DS_DEFS_VH
`define DS_DEFS_VH

`include "ds_gen.vh"

//-----------------------------------------------------------------------------
// Datapath widths
//-----------------------------------------------------------------------------
// int8 activations and weights; int32 accumulators. rtl_spec.md section 4 shows
// the widest layer sums 192 products of 127 x 128, worst case 3,121,152 -> 23
// bits, so an int32 accumulator CANNOT overflow and the MAC path carries no
// saturation logic. The clamp at the int8 output is the only saturating operation
// in the design.
`define DS_ACT_W    8       // activation, signed
`define DS_WGT_W    8       // weight, signed
`define DS_ACC_W   32       // accumulator, signed (int32, per the export)

// The global average pool sums DS_POOL_N accumulators before requantising.
// Worst case 32 x 3,149,695 = 100,790,240 -> 28 bits signed (rtl_spec.md s4),
// so it also fits the same int32 accumulator and needs no wider register.
`define DS_POOL_N  32

// Requantisation product: M0 (DS_FRAC_W bits, unsigned, from ds_gen.vh) times a
// relu'd accumulator (DS_ACC_W bits, signed).
`define DS_PROD_W  (`DS_FRAC_W + `DS_ACC_W)
// Right-shift amount. The generated shifts reach 40, so 6 bits is enough, and 6
// is also what makes {shift, m0} fit one 32-bit word in ds_param_mem at
// DS_FRAC_W = 26. gen_rtl_params.py asserts both facts rather than trusting them.
`define DS_SHIFT_W  6

//-----------------------------------------------------------------------------
// Index widths in the layer engine
//-----------------------------------------------------------------------------
// Shared between ds_conv1d, ds_ctrl_fsm, ds_core and ds_top so that a port and
// the register that drives it cannot disagree. Macros rather than module
// parameters because they appear in PORT LISTS, which a localparam declared in
// the module body is too late for.
//
// DS_CFG_W  lengths and counts in the layer descriptor: the 512-bin input axis
//           and the 192-term widest reduction both fit 10 bits.
// DS_CH_W   channel indices: every layer's O and I are at most 64.
// DS_K_W    kernel tap index: K is at most 9.
`define DS_CFG_W  10
`define DS_CH_W    7
`define DS_K_W     4

//-----------------------------------------------------------------------------
// Activation storage
//-----------------------------------------------------------------------------
// Two ping-ponged buffers. The largest intermediate activation is 4,096 int8
// bytes -- conv1, conv2 and conv3 each produce exactly 4,096 (rtl_spec.md s6) --
// and the 5 x 512 input is 2,560, so 4,096 covers every stage.
//
// Within a buffer the layout is channel-major: addr = channel * L + position.
// That is the layout the reduction loop wants, because for a fixed input channel
// the K taps of a kernel are at consecutive addresses.
`define DS_ACT_DEPTH  4096
`define DS_ACT_AW     12    // $clog2(4096)

//-----------------------------------------------------------------------------
// Layer table -- indices into the unified weight and bias memories
//-----------------------------------------------------------------------------
// Five layers, run in order. The engine is one datapath; "fc" is layer 4 with
// I = 64, K = 1, L_in = L_out = 1, which is arithmetically the same reduction as
// a convolution and does not justify a second multiplier.
`define DS_N_LAYERS  5
`define DS_L_CONV1   0
`define DS_L_CONV2   1
`define DS_L_CONV3   2
`define DS_L_CONV4   3
`define DS_L_FC      4

// Per-layer flags carried alongside the table
`define DS_F_POOL    0      // accumulate over output positions, then requantise
`define DS_F_LAST    1      // no requantisation: scale and hand to the argmax

//-----------------------------------------------------------------------------
// AXI-Lite register map (byte offsets)
//-----------------------------------------------------------------------------
`define DS_REG_CTRL     8'h00   // W  bit0 start (self-clearing), bit1 soft reset
`define DS_REG_STATUS   8'h04   // R  see below
`define DS_REG_CLASS    8'h08   // R  argmax index, 0..2
`define DS_REG_LOGIT0   8'h0C   // R  scaled logit, int32, LSB = 2^DS_LOGIT_LSB_EXP
`define DS_REG_LOGIT1   8'h10   // R
`define DS_REG_LOGIT2   8'h14   // R
`define DS_REG_BUILDID  8'h18   // R  CRC-32 of the weights+biases actually loaded
`define DS_REG_CYCLES   8'h1C   // R  clock cycles of the last inference
`define DS_REG_MAGIC    8'h20   // R  DS_MAGIC, identifies the core
`define DS_REG_CONFIG   8'h24   // R  {8'h0, LOGIT_SHIFT, LANES, FRAC_W}

// STATUS bits
`define DS_ST_DONE      0       // inference complete, sticky until the next start
`define DS_ST_BUSY      1       // compute engine running
`define DS_ST_IDLE      2       // ready to accept a start
`define DS_ST_IN_VALID  3       // a full 2,560-byte input frame has been received
`define DS_ST_CRC_DONE  4       // the build-ID walk has finished; BUILDID is valid

`define DS_MAGIC     32'h44533031   // "DS01"

`endif // DS_DEFS_VH
