//===========================================================================
// ds_gen.vh -- GENERATED by scripts/rtl/gen_rtl_params.py. DO NOT EDIT.
//===========================================================================
// Everything here is a property of artifacts/int8_export/, not of the
// architecture. Re-export the model and regenerate; never hand-edit.
// tests/test_rtl_generated.py regenerates this file and fails if the
// committed copy differs.
//
// fractional width : 26   (chosen by bit_exact_confirm.json;
//                     docs/rtl_declarations.md D-2 states the rule)
// weights          : 27,024 int8
// biases           : 179 int32
//===========================================================================

`ifndef DS_GEN_VH
`define DS_GEN_VH

// ---- requantisation -------------------------------------------------
`define DS_FRAC_W      26
`define DS_FC_SHIFT    39   // one shared shift for the 3 classes
`define DS_LOGIT_SHIFT 16   // raw product -> the int32 register
`define DS_LOGIT_LSB_EXP -23  // register LSB = 2**this, in the reference's float units

// ---- memory geometry -------------------------------------------------
`define DS_W_DEPTH     27024
`define DS_B_DEPTH     179
`define DS_WGT_AW      15
`define DS_PAR_AW      8
`define DS_IN_BYTES    2560

// ---- exported memory images, read unchanged --------------------------
`define DS_W0_FILE     "artifacts/int8_export/layer_0_W.mem"
`define DS_W1_FILE     "artifacts/int8_export/layer_1_W.mem"
`define DS_W2_FILE     "artifacts/int8_export/layer_2_W.mem"
`define DS_W3_FILE     "artifacts/int8_export/layer_3_W.mem"
`define DS_W4_FILE     "artifacts/int8_export/layer_4_W.mem"

`define DS_B0_FILE     "artifacts/int8_export/layer_0_b.mem"
`define DS_B1_FILE     "artifacts/int8_export/layer_1_b.mem"
`define DS_B2_FILE     "artifacts/int8_export/layer_2_b.mem"
`define DS_B3_FILE     "artifacts/int8_export/layer_3_b.mem"
`define DS_B4_FILE     "artifacts/int8_export/layer_4_b.mem"

`define DS_PARAM_FILE   "rtl/mem/requant_params.mem"   // GENERATED, not exported

// ---- base offsets into the unified memories --------------------------
`define DS_W0_BASE     0
`define DS_W1_BASE     720
`define DS_W2_BASE     4304
`define DS_W3_BASE     14544
`define DS_W4_BASE     26832

`define DS_B0_BASE     0
`define DS_B1_BASE     16
`define DS_B2_BASE     48
`define DS_B3_BASE     112
`define DS_B4_BASE     176

// ---- layer table -----------------------------------------------------
// O  out channels | I in channels | K taps | LIN/LOUT length along the
// order axis | DSTL destination stride | TERMS = I*K, so ds_conv1d needs
// no multiplier | POOL conv4 | LAST fc
// layer 0: conv1  184,320 MACs
`define DS_L0_O        16
`define DS_L0_I        5
`define DS_L0_K        9
`define DS_L0_LIN      512
`define DS_L0_LOUT     256
`define DS_L0_DSTL     256
`define DS_L0_STRIDE   2
`define DS_L0_PAD      4
`define DS_L0_TERMS    45
`define DS_L0_POOL     0
`define DS_L0_LAST     0
// layer 1: conv2  458,752 MACs
`define DS_L1_O        32
`define DS_L1_I        16
`define DS_L1_K        7
`define DS_L1_LIN      256
`define DS_L1_LOUT     128
`define DS_L1_DSTL     128
`define DS_L1_STRIDE   2
`define DS_L1_PAD      3
`define DS_L1_TERMS    112
`define DS_L1_POOL     0
`define DS_L1_LAST     0
// layer 2: conv3  655,360 MACs
`define DS_L2_O        64
`define DS_L2_I        32
`define DS_L2_K        5
`define DS_L2_LIN      128
`define DS_L2_LOUT     64
`define DS_L2_DSTL     64
`define DS_L2_STRIDE   2
`define DS_L2_PAD      2
`define DS_L2_TERMS    160
`define DS_L2_POOL     0
`define DS_L2_LAST     0
// layer 3: conv4  393,216 MACs
`define DS_L3_O        64
`define DS_L3_I        64
`define DS_L3_K        3
`define DS_L3_LIN      64
`define DS_L3_LOUT     32
`define DS_L3_DSTL     1
`define DS_L3_STRIDE   2
`define DS_L3_PAD      1
`define DS_L3_TERMS    192
`define DS_L3_POOL     1
`define DS_L3_LAST     0
// layer 4: fc  192 MACs
`define DS_L4_O        3
`define DS_L4_I        64
`define DS_L4_K        1
`define DS_L4_LIN      1
`define DS_L4_LOUT     1
`define DS_L4_DSTL     1
`define DS_L4_STRIDE   1
`define DS_L4_PAD      0
`define DS_L4_TERMS    64
`define DS_L4_POOL     0
`define DS_L4_LAST     1

`endif // DS_GEN_VH
